### PR TITLE
4b19sd1.1

### PR DESCRIPTION
**Pull request by subtledoctor**
sleep wake-up fix: changed wake-up contingency from "on hit" to "took damage"

### CODE REVIEW

**Comment by lambda-dom** [comment]
@subtledoctor could you tell me what the fix was specifically, just to know what my eyeballs should be looking at and to document it.

**Comment by subtledoctor** [comment]
Yes exactly - change the subspell's condition from "hit" to "took damage." also unchecked the EE "wake on damage" flag since we have the subspell handling that. As for the subspell, I honestly don't recall... might have just changed the order of the two effects?

**Comment by subtledoctor** [comment]
Oh I see the difference: it looks like the revised version of SPWI116D has timing mode 4 with a 1-second delay. I think I added that for a small semblance of verisimilitude - the original SR version (and the EE wake-on-damage flag) create a weird-looking thing where when a sleeping person is scratched, they suddenly teleport to their feet and are already swinging their sword at the enemy. Being woken up by a hit - or even getting up from a knockdown - is not really like that. So I added a 1-second delay, just so that it isn't so oddly immediate.

Frankly I think it would make more sense to go a bit further than that. A 1-2 second effect setting APR to zero, and maybe a brief casting speed penalty, would make sense. For my own mod, I actually apply a 2-second Slow effect, which actually makes it seem like the sleeping person is getting to their feet. And it also makes them a bit more vulnerable during that process, which I like.

Adding a Slow or APR effect would be a serious editorial change, which I don't want to do without more discussion. (And frankly my own mod overwrites SR's behavior here so I don't personally care.) So I just tweaked the timing slightly. But if you think that is also too much of a change, I understand.

**Comment by BartyMae** [comment]
IIRC, enemies that fall asleep in the middle of casting spells can wake up and resume the spell they were in the middle of casting as well, can they not?

**Comment by BartyMae** [comment]
@subtledoctor At least for the EEs, they do not wake up and resume spellcasting. Though I have a question: why does sleep have this special wake-up subspell in the first place? Power Word: Sleep and Command don't, so why Sleep?

**Comment by subtledoctor** [comment]
> @subtledoctor At least for the EEs, they do not wake up and resume spellcasting. Though I have a question: why does sleep have this special wake-up subspell in the first place? Power Word: Sleep and Command don't and enemies wake up the same as Sleep do, so why does Sleep?

I don't know - this is how Demi made it. This is really designed for the pre-EE engine. If you are suggesting that SR keep the current behavior on pre-EE installs (I'm not aware of anyone reporting it as buggy there) and eliminating the contingency on EE installs and just using the EE "wake on hit" flag instead... I guess sure? Using a contingency and a subspell gives you more flexibility in how to actually implement the wakeup; it's what I use in my mod. But SR does not currently take advantage of that flexibility, so... I suppose simpler is better. 

(Though, arguably, keeping the subspell is in fact simpler since it allows for uniform installation on both EE and pre-EE games.)

So either 1) change the contingency from "hit" to "took damage" *or* 2) remove the contingency in EE installs and check the "wake on hit" flag." I'm god with either option. If you prefer #2, I can make up a pull request for it.

**Comment by BartyMae** [comment]
@subtledoctor It's not necessary for pre-EE games with ToBEx (which SR automatically installs?) either: I tested by casting Power Word: Sleep on a hobgoblin and then throwing a dart at it, and he woke up immediately. So by my estimation, it would seem to make more sense to either A. change all sleep effects (Sleep, Power Word: Sleep, Command?) to have the momentary delay, or B. be rid of it entirely on Sleep. I don't really mind either way, but having it only apply to Sleep seems odd to me - I would assume that the sub-spell still existing is simply a remnant of the pre-ToBEx days that nobody ever cleaned up.

**Comment by lambda-dom** [comment]
Apologies, but I am away most of August and with little to no internet access, so have been delaying this.

@subtledoctor: why not add the condition on both Command and Power Word Sleep?

@bartymae: what is the prevalence of non-EE installs with ToBEX vs. without? I think I commented on this issue with sleep in the G3 site, that SR should maintain backwards compatibility and a functioning SR install in non-EE. The condition solution has the advantage of being uniform but it is also possible to, on EE installs, to add in the post-processing phase code to extirpate the condition and just rely on the wake flag.

**Comment by BartyMae** [comment]
I would wager most non-EE hanger-ons like myself use ToBEx, particularly because of its necessity for a number of important mods. Even if users don't actively install it, Spell Revisions itself does by default (see settings.ini: "install_tobex = 1").

**Comment by subtledoctor** [comment]
I think it's reasonable that the "wake-on-damage" process - via whatever mechanism - is omitted from Command. The duration of Command is already so short, and the fluff text suggests the target is not put to sleep, per se, but mentally convinced that they have died. 

PW:Sleep is a weird one - it's weird in general. But I'll note that it is a higher spell level than Sleep, and vastly more limited in who it can target, and the description mentions being not just asleep but "comatose." So maybe there, too, Demi intentionally excluded it from the wake-on-damage process. And that seems reasonable to me.

EDIT - actually the 1st-level Sleep spell description also says "comatose." So I don't know. PW:Sleep is a stupid spell IMHO, I don't really care. I suppose we should follow the rule of "sleep is sleep" and therefore give it the same wakeup conditions as Sleep.

**Comment by BartyMae** [comment]
I would agree that Command should not allow the enemy to awake (and possibly Power Word Sleep as well, though doing that might require some re-consideration of its duration), but I don't know how you would implement that on pre-EE games - once hit, an enemy **always** wakes up. EE games have the option of using the secondary mode for the unconsciousness opcode that allows an enemy to not wake up, but this is not implemented in ToBEx. This is a highly intriguing idea to me, so if you have any ideas on how you would make it so Command always last the requisite 1 round, I'd be all ears.

**Pull request closed without merging**
