### PR TITLE
Sanctuary/Invisibility-breaking component for EE 2.6

### PR DESCRIPTION
**Pull request by BartyMae**
Taken directly from SRR, it probably needs tweaks and could use some extra eyes. Admittedly very simply coded, but it works. Only included are hostile/summon spells/scrolls as that's how the EEs currently function (though I've commented out some others that perhaps could have consideration, such as Dimension Jump, Detect Alignment, Fire Shield, etc.).

### CODE REVIEW

**Comment by lambda-dom** [comment]
Will take a look at it this weekend, barring unexpected events (been AFK most of the month). At any rate, could you add a description of what it is that you are trying to do? A link to forum discussions will do as well.

**Comment by subtledoctor** [comment]
I think it might be better to run this from a human-readable .2da file. That way the player can pretty easily change this to suit their own preferences. Could even make templates for different systems - "friendly spells don't break invisibility," "all spells break invisibility except healing spells," etc. I'm putting the finishing touches on it now, should have something ready for review soon.

Relevant discussion: 
https://www.gibberlings3.net/forums/topic/33184-ee-26-vs-spl-v1-break-sanctuary-flag/?tab=comments#comment-298632

**Comment by subtledoctor** [comment]
It's weird, a lot of stuff in BGEE v2.6.6 that seems pretty hostile, does not have the hostile flag. Meteor Swarm, PW Kill, Imprisonment, all the Symbol spells... am I missing something, or shouldn't they be tagged as hostile?

**Comment by BartyMae** [comment]
> 
> 
> It's weird, a lot of stuff in BGEE v2.6.6 that seems pretty hostile, does not have the hostile flag. Meteor Swarm, PW Kill, Imprisonment, all the Symbol spells... am I missing something, or shouldn't they be tagged as hostile?

Yes, and they are in the original game and with SR's .spls. So why did Beamdog decide to untag them as hostile?

**Comment by subtledoctor** [comment]
> Yes, and they are in the original game and with SR's .spls. So why did Beamdog decide to untag them as hostile?

Probably because they do damage, and application of opcode 12 has the same effect? Maybe?

Anyway, I submitted my alternative implementation of this, feel free to take a look.

**Pull request closed without merging**
