### PR TITLE
Level 8 spell fixes

### PR DESCRIPTION
**Pull request by lambda-dom**
- Ghostform: play visual opcodes have power 6 -> 8. Misses protection from strings 54337 = "Diseased", 17398 = "Nauseated", 14662 = "Poisoned"
- Mind Blank: misses immunity to stun and berserk, protection from icons: 2 = Rigid Thinking, 4 = Berserk , 55 = Stun. Isses protection from strings: 14672 = "Charmed", 14780 = "Dire Charmed", 14102 = "Held", 14650 = "Paralyzed", 23744 = "Feebleminded", 14665 = "Petrified", 1280 = "Stunned", 340 = "Held", 1473 = "Held"
- Symbol of Weakness: save penalty -6 -> -4.
- Horrid Wilting: undocumented protection for elemental creatures; removed it.
- Symbol of Death: opcode save penalty -6 -> -4.
- Bigby's Icy Grasp: in aux spell, opcodes hold and play visual have wrong saves (-4 and 0) -> -2. The resist_dispel in setting up hold are also inconsistent: put all at 1, but this is something of a guess. Use Eff opcodes timing mode 1 -> 0 so it does not block subsequent hits.

Description Fixe(s):
- Spell Thrust (level 3), Secret Word (level 4), Pierce Magic (level 6), Ruby Ray of Reversal (level 7), Khelben's Warding Whip (level 7) are advertized as removing Dispelling Screen, but this is not true, so deleted it. For to remove it, they would have to, for example, have an opcode to remove spell by sectype for k1#dispel which they do not have, nor anything similar -- k1#dispel is set by k1#scre spell, an aux spell of Dispelling Screen that is *not* a spell protection. This is also hinted at the wording of Dispelling Screen, that only high-powered spell protection removal spells bring down dispelling screen. Furthermore, Pierce Shield *explicitly* dispels k1#dispel in the last opcode in the first spell it casts.

Note(s):
- Moment of Prescience: mention that is not dispellable?
- Pierce Shield: all but 1 opcode in the first aux spell have power 0. There is an inconsistency here as spell thrust, secret word and pierce magic have the same 0 power, while RRoR and Khelben's Warding Whip have power 7 and Spellstrike has power 9. Need guidance to sort this out. Barty_Mae suggests standardize power 0, which is what I think best. The problem is that the casting spell opcodes and the aux spells seem to be generated at install time and in some cases, it is not even clear that that they should have 0 power. Should the miscast effect of spellstrike have power 0? Probably not.
- Power Word Blind: Protection from obscuring mist and power word blind lack the minimum level. Only the 1 turn version of protection from spells exist, with the exception of Power Word Blind. Have not done anything because many of these protections are added at install time.
- Bigby's Icy Grasp: in aux spell, the play visual and damage opcodes are applied before setting up immunities, is this correct? At any rate, description should mention that a whole bunch of critters are immune to the hold effect.

### CODE REVIEW

**Comment by BartyMae** [comment]
Mind Blank: It's not clear whether stun should be included here. It should almost definitely protect against e.g. psionic stunning, but "physical" stunning is another question and is probably why it was left out. Personally, it's a level 8 protection spell, I'd be pretty okay with it protecting against all forms of stunning. Another note is that I don't think, with the exception of the berserking two-handed sword, that berserking is used as a weaponized effect, right? So basically you'd just be disabling fighter/mages from properly using their berserking ability.

Horrid Wilting: Should probably be the other way around: the protection should be documented in the spell, and the protection should probably extend to other types of non-biological creatures like constructs and illusions like other diseasing and draining spells.

Anti-magic power levels: set to 0, IMO.

**Comment by lambda-dom** [comment]
> Mind Blank: It's not clear whether stun should be included here. It should almost definitely protect against e.g. psionic stunning, but "physical" stunning is another question and is probably why it was left out. Personally, it's a level 8 protection spell, I'd be pretty okay with it protecting against all forms of stunning. Another note is that I don't think, with the exception of the berserking two-handed sword, that berserking is used as a weaponized effect, right? So basically you'd just be disabling fighter/mages from properly using their berserking ability. (e): Wait, I think SR's Chaos might.
> 

My justification: it protects against power word stun. IR's greenstone's amulet, that has a similar function, also protects against it, and more generally stun tends to be bundled together with immunities against hold (e.g. Chaotic Commands). And yes, one of the effects of chaos is berserk.

> Horrid Wilting: Should probably be the other way around: the protection should be documented in the spell, and the protection should probably extend to other types of non-biological creatures like constructs and illusions like other diseasing and draining spells.
> 

I thought of that, given the description (something about moisture). Two concerns however: (1) for example, elementals include creatures like salamanders that should not be immune to it (2) over-nerfing. So for now I am sitting this one out, though I tend to favor your opinion.

> Anti-magic power levels: set to 0, IMO.

Yeah, that is probably the best solution.

**Comment by BartyMae** [comment]
I decided on leaving berserking out of its immunities, and simply protecting against Chaos entirely. 

@Stunning: Power Word Stun fits under the "power word" umbrella, though. IIRC, Chaotic Commands didn't until very recently protect against stun as well, but kreso decided to let it as of his very last version of SR. I don't think he even updated the description to say that it did. It should be noted that one of his next planned changes was to nerf Mind Blank so that it didn't protect against divination spells or hold effects, for reasons unknown to everyone else, because even with protection against stunning, this spell at 8th level still isn't exactly great (...which is why I'm ultimately for it receiving the protection).

**Comment by BartyMae** [comment]
Bigby's Icy Hand: Now that I got a look at it, I think you'll have to revert this one. SPWI818D's effects are set to resist 2 because the MR check is done at the "cast spell" opcode level in SPWI818 instead, so switching it to 1 there would subject the spell to duplicate MR checks. I thought about switching it around so that it's 1 for the D.spl and 2 for the main spell, but that means the targeted creature would have to make an SR check every round instead of simply the initial cast, which is a big change.

The immunities are properly set. Basically, it puts the immunities after the damage but before the holding, so that some creatures will be immune to the holding but will still get smacked by the damage.

**Comment by lambda-dom** [comment]
> Bigby's Icy Hand: Now that I got a look at it, I think you'll have to revert this one. SPWI818D's effects are set to resist 2 because the MR check is done at the "cast spell" opcode level in SPWI818 instead, so switching it to 1 there would subject the spell to duplicate MR checks.

That is not what I am seeing at NI. The cast spell opcodes have resist_dispel 0.

> The immunities are properly set. Basically, it puts the immunities after the damage but before the holding, so that some creatures will be immune to the holding but will still get smacked by the damage.

Then description should reflect this.

**Comment by BartyMae** [comment]
I have a mildly revised version of Icy Grasp in SRR, so that's likely my bad. In that case, yeah, setting to 1 there is most likely correct (although based on other spells of "an effect applied every round", the MR check *should* be in the base spell, which is what I opted for, but whatever).

**Comment by lambda-dom** [comment]
> Anti-magic power levels: set to 0, IMO.

Unfortunately things seem to be a tad more complicated. See my revised PR comments on why.

**Comment by lambda-dom** [comment]
> although based on other spells of "an effect applied every round", the MR check _should_ be in the base spell, which is what I opted for, but whatever.

Doesn't this approach makes those effects undispellable if the casting opcode passes the mr check? And is that the intended effect?

**Comment by BartyMae** [comment]
To fix that, you would simply go into ardanis_spell_shield.tph and go to the "WRITE_BYTE  (offset+0x03) power   // power level" line, and change "power" to 0. However, I must admit, that I am no longer sure that this is the best approach - I'm not sure what the actual effect is in practice, if any, so probably wait for further testing on that one.

Bigby's: No, they'd still be dispelable, but it would instead be the delayed "cast spell" opcodes you'd be dispelling (which would mean, if dispelled, would stop further grasps from affecting the target).

**Comment by BartyMae** [comment]
From further testing, I don't think the power level makes any difference at all. Any spell that has the 4 sectype (MAGICATTACK) appears to be hardcoded to passthrough spell protections (tested by setting Larloch's Minor Drain to sectype 4 and using it against Spell Trap, went straight through when it previously hadn't). So...that's that.

**Comment by lambda-dom** [comment]
> From further testing, I don't think the power level makes any difference at all. Any spell that has the 4 sectype (MAGICATTACK) appears to be hardcoded to passthrough spell protections (tested by setting Larloch's Minor Drain to sectype 4 and using it against Spell Trap, went straight through when it previously hadn't). So...that's that.

Ok, doing nothing then for now. I will leave the note in the PR and if Mike has a different opinion then I can go from there.

**Comment by BartyMae** [comment]
Note that I made an edit seconds before your post:
"Wait a second: while it is true they may be hardcoded to go through spell protections, perhaps outright level protections like liches have could be affected?"

**Comment by lambda-dom** [comment]
> Note that I made an edit seconds before your post:
> "Wait a second: while it is true they may be hardcoded to go through spell protections, perhaps outright level protections like liches have could be affected?"

Missed it. But since I do not know the answer, sitting still until more info is in. I remember DavidW saying that we should face a lich with SCS + SR and without Pierce Shield (level 8) because Breach is blocked being a level 5 spell. I would assume the same principle applies to spell protection removals, but I really do not know.

**Comment by BartyMae** [comment]
I just tested it: power level 0 Secret Word affects lich01.cre, power level 6 Secret Word does. Therefore, setting them all to their proper power level is indeed important.

**Comment by BartyMae** [comment]
...Also, another thing: that implementation of Bigby's Icy Grasp is messed up and inconsistent. So basically, if it were one of the immunized creatures (e.g. an elemental), it would get smacked for 2D8 cold damage the first round, but wouldn't be subject to the hold effect. The thing is, the immunizing effect immunizes the creature permanently, meaning that subsequent fires of the spell will do absolutely nothing, not even the damage, because it has been wholesale immunized against it. So the damage and the hold effect would actually need to be separated into two different subspells in order for this to work properly.

**Comment by lambda-dom** [comment]
> ...Also, another thing: that implementation of Bigby's Icy Grasp is messed up and inconsistent. So basically, if it were one of the immunized creatures (e.g. an elemental), it would get smacked for 2D8 cold damage the first round, but wouldn't be subject to the hold effect. The thing is, the immunizing effect immunizes the creature permanently, meaning that subsequent fires of the spell will do absolutely nothing, not even the damage, because it has been wholesale immunized against it. So the damage and the hold effect would actually need to be separated into two different subspells in order for this to work properly.

Wouldn't changing the timing mode of the Use Eff opcodes instant -> limited work? I *think* duration 0 is enough to block the rest of the spell, which is what is needed, but duration 1 is equally good -- assuming a positive answer to the question, that is.

I have been avoiding delving into SR code as much as possible, because weidu is not exactly the friendliest of languages, and diving naked into a full codebase is always painful (and programming is not even my specialty), but it seems unavoidable at this point.

**Comment by BartyMae** [comment]
Yeah, I guess that should work, too.

**Pull request closed without merging**
