### PR TITLE
Arcane level 5 spell fixes

### PR DESCRIPTION
**Pull request by lambda-dom**
## Arcane Level 5 spell fixes.

1. Summon Shadow: summoning eff power corrections 6 -> 0.
2. Monster Summoning V: summoning eff power 6 -> 0.
3. Shadow Door: opcode 215 resist_dispel 0 -> 3.
4. Mental Domination: first 174 play sound opcode lacks save. Fix save penalty -4 -> the documented -2.
5. Hold Monster: lacks portrait icon and display string opcodes.
6. Breach: Description fixes: mind blank missing from the specific protections list; moment of prescience missing from the combat protections list.
7. Protection from Electricity: cast as a subspell of Protection from Elemental Energy but coded as a level 5 spell: level 5 -> 4, power of opcodes 5 -> 4. Being coded as a level 5 spell, it misses two headers and the durations of the first header have to be fixed. Description fix.
8. Conjure Lesser Fire Elemental: The first play visual effect opcode (that should play on a successful summon) has the wrong probability 86 - 100 -> 0 - 85. Summoning eff power correction 5 -> 0.

note(s):
* there are off-by-one errors in probability fields literally everywhere (the engine rolls a number in the range 0-99, so that 99 and 100 are functionally the same). Not worrying about it now, as the best way to tackle this is to do a systematic, focused sweep.

9. Protection from Acid: same problems as Protection from Electricity.
10. Phantom Blade: create weapon opcode amount 0 -> 1.
11. Conjure Lesser Air Elemental: same problem as Conjure Lesser Fire Elemental. Summoning eff power correction 5 -> 0.
12. Conjure Lesser Earth Elemental: same problem as Conjure Lesser Fire Elemental. Summoning eff power correction 5 -> 0.
13. Waves of Fatigue: fixed ability icon with incorrect transparency layer by using SRR corrected version.

### CODE REVIEW

**Comment by BartyMae** [comment]
Breach: Moment of Prescience is arguably not a combat protection, but if SR currently has it set as one, I suppose it makes sense to currently mention it in the description.

Domination: I almost feel like Domination should stay at the "incorrect" -4 penalty, not -2. Compare to Feeblemindedness at the same level and in the same school that has a -4 penalty that essentially acts as an instant death spell against the AI (as they have no way to dispel it) as opposed to a 1 turn charm. Additional, clerics have Mental Domination at 4th spellcasting level and have the -2 penalty already, which makes using the same penalty at 5th level when you have so many other better spells a bit of a tough pill IMO.

**Comment by subtledoctor** [comment]
Re: Breach, I'll only note that I have a mod that allows players to change whether Moment of Prescience is a combat protection, whether Fire Shield is a specific protection, etc. I don't love the idea that the Breach spell description must include mention of every spell it removes since it is easy to change that list, thus rendering Breach's spell description inaccurate, even when you don't modify Breach itself.  And spell descriptions are super annoying to patch, especially given that different mods are often translated into different lists of languages. I think a better option would be to say Breach "removes combat protections such as A/B, and specific protections such as X/Y." Then mention spell sectypes in their own spell descriptions.  (There is a strong argument for the latter in any event - judging by forum discussions, many players are not very familiar with the sectype of each spell.)

Domination: problem is, a successful Domination is more useful than a successful Feeblemind, since you gain an ally as well as removing an enemy from the board.  There has long been a serious balance issue with 5th-level Enchantment spells, any adjustments should probably be considered holistically. Probably worth rfc/public discussion in the forums.

**Comment by BartyMae** [comment]
I think the point of listing literally every spell that anti-magic spells work against serves the very point you mention re: players not understanding what sectypes are and how they apply. It's a little cumbersome, but at least it's clear. There might be an alternative way to handle it in regards to introducing an entire secondary type text field in every spell, but that's kind of cumbersome too, especially since it only meaningfully affects such a tiny fraction amount of spells.

Domination/Feeblemind: Depends on whom and what circumstances it's cast, I suppose. Situations like this are always funny to me when considering the "only fix stuff, don't make conceptual changes" ideal of doing maintenance work like this: though the description may have always been saying it was -2, if the spell has actually been -4 for the past ten years or whatever, what has actually been the long-accepted implementation?

**Comment by lambda-dom** [comment]
> I think the point of listing literally every spell that anti-magic spells work against serves the very point you mention re: players not understanding what sectypes are and how they apply. It's a little cumbersome, but at least it's clear.

Right. But there must be a better way to do this. Conceptually, it is a matter of listing the spells of a given sectype and then patching the description at install time with the generated list.

> Domination/Feeblemind: Depends on whom and what circumstances it's cast, I suppose. Situations like this are always funny to me when considering the "only fix stuff, don't make conceptual changes" ideal of doing maintenance work like this: though the description may have always been saying it was -2, if the spell has actually been -4 for the past ten years or whatever, what has actually been the long-accepted implementation?

subtledoctor has a point; just spitballing here, but instead of increasing the save penalty of Domination why not decrease that of feeblemind?

**Comment by BartyMae** [comment]
Patching descriptions instead: if you can figure out how to do it (and account for multiple languages?), then by all means, I suppose!

I actually used to do exactly that in SR, but I received a few complaints about it over the years, sat and thought about it, and realized that almost everything strong is usually immune to both feeblemindedness AND charm anyways, plus you have Confusion sitting there at 4th level for a huge AoE disable at the same saving penalty (plus less are immune to confusion than feeblemindedness/charm), so I said screw it and increased them back up to -4.

**Pull request merged**
