### PR TITLE
Divine level 1 fixes

### PR DESCRIPTION
**Pull request by lambda-dom**
## Divine Level 1 spells.

1. Command: play sound opcode lacks save vs. spell and respective save penalty. Self-targeted play visual opcode resist_dispel -> 0.
2. Cure Light Wounds: add remove intoxicated icon opcode since the spell also cures intoxication.
3. Entangle: duration of opcodes 8 -> 7 to conform with similar cloud spells. See Kjeron's comments in the thread [SR fixes questions](https://www.gibberlings3.net/forums/topic/30963-sr-fixes-questions).
4. Sanctuary: play sound opcode delay 60 -> 36.
5. Shilellagh: create item opcode amount 0 -> 1.

note(s):
* set profs opcode is in the spell, not in the item as it is usual. Since as far as I can see there is no practical difference, choosing the conservative route and doing nothing.

6. Good Berry: power of opcodes 2 -> 1.
7. Cause Light Wounds: power of opcodes 4 -> 1.
8. Regenerate Light Wounds: resist_dispel -> 3 as description explicitly says spell is dispellable. Only headers 7 and higher have Display String "Regenerating" -- added missing opcodes.
9. Strength of Stone: misses protection from druid version of Gust of Wind.

note(s):
* the description says "For the duration of the spell, the caster also becomes immune to everything, magical or otherwise, that pushes him away" which is implemented with immunity to Wing Buffet (235). If this catches all the relevant cases, why add protection from the likes of Gust of Wind? Gust of Wind, the druid version only (fixed in the relevant PR), also dispels insects, do we want that? On the other hand, knockback effects (say from Smite HLA or Dragon's Wing Buffet) usually causes stun/unconsciousness so it makes sense to protect against those. And if it does not catch all relevant cases, what is missing? Leaving this as a note to self, as I have not thought this through.

note(s): see discussion below with Bartimeus:
* moved knockback in Gust of Wind to a subspell (see relevant PR), and replaced protections from Gust of Wind to protection from subspell.

10. Obscuring mist: remove spurious 284 opcode with probability 0 (relevant penalties are implemented in other opcodes). resist dispel 1 -> 2 for 0 and 164 opcodes, as the penalties are from the cloud and thus should not be blocked by mr or dispellable. Fixed bam with messed up transparency layer by using SRR bam.

note(s):
* the description says "Everyone within the cloud suffer -2 penalty to attack rolls, and have their line of sight halved. Anyone, inside or outside the cloud, trying to attack a creature concealed by the fog with ranged weapons will do so with a -4 penalty to attack rolls. Creatures with blindsight, or that do not rely on sight can fight within the cloud without penalties." The former is implemented with a penalty to thaco0 and a bonus to missile ac to everyone inside the cloud. The latter is implemented (or should be) by the proper immunities (in spells like True Seeing, specific cre's like bats, etc.) -- note to future self.
* funny note: WeiDU reports: "-1 effect(s) deleted" huh...

### CODE REVIEW

**Comment by BartyMae** [comment]
Command: The self-targeting VFX should not have a saving throw (i.e. it should always play regardless of whether the target saves or not). It doesn't look like you changed that, so it's correct as-is.

Gust of Wind: Should continue to dispel insects (it's not as though Gust of Wind is particularly powerful to begin with), and IMO, that includes against Strength of Stone-affected creatures. I'm unsure if Strength of Stone should protect against unconsciousness from effects like Smite - may depend on a case-by-case basis based on flavor text...but for simplicity's sake, I wouldn't be against it either.

**Comment by lambda-dom** [comment]
> Command: The self-targeting VFX should not have a saving throw (i.e. it should always play regardless of whether the target saves or not). It doesn't look like you changed that, so it's correct as-is.

Right, have not changed it.

> Gust of Wind: Should continue to dispel insects (it's not as though Gust of Wind is particularly powerful to begin with and it thematically fits), and IMO, that includes against Strength of Stone-affected creatures. I'm unsure if Strength of Stone should protect against unconsciousness from effects like Smite - may depend on a case-by-case basis based on flavor text...but for simplicity's sake, I wouldn't be against it either.

This poses the problem then that Strength of Stone must block the knockback from Gust of Wind but not its dispel insects. Which suggests dropping the protection from spell and hope that the immunity to wing buffet is enough (have not checked). Assuming it is enough, I actually favor this solution.

**Comment by BartyMae** [comment]
> 
> 
> > Command: The self-targeting VFX should not have a saving throw (i.e. it should always play regardless of whether the target saves or not). It doesn't look like you changed that, so it's correct as-is.
> 
> Right, have not changed it.
> 
> > Gust of Wind: Should continue to dispel insects (it's not as though Gust of Wind is particularly powerful to begin with and it thematically fits), and IMO, that includes against Strength of Stone-affected creatures. I'm unsure if Strength of Stone should protect against unconsciousness from effects like Smite - may depend on a case-by-case basis based on flavor text...but for simplicity's sake, I wouldn't be against it either.
> 
> This poses the problem then that Strength of Stone must block the knockback from Gust of Wind but not its dispel insects. Which suggests dropping the protection from spell and hope that the immunity to wing buffet is enough (have not checked). Assuming it is enough, I actually favor this solution.
> 
> Edit: just went and look and Gust of Wind also has a Sleep opcode for unconsciousness. The dispel insect stuff is I presume, added later on, when adding the new sectype and allied matters. So we got a bit of a problem here. I suppose this could be solved by complicating the implementation by using a subspell but then it is bound to cause problems somewhere down the line.

Yeah, I actually already do exactly this (put the unconsciousness and knockback opcodes) in a subspell in SRR - called it "dvgustwi.spl".

**Comment by lambda-dom** [comment]
> Yeah, I actually already do exactly this (put the unconsciousness and knockback opcodes in a subspell) in SRR - I called it "dvgustwi.spl", as it's easier if it's a static resource name.

I will do just that -- or better yet, save myself some trouble and shamelessly steal your implementation.

**Comment by subtledoctor** [comment]
I don't completely hate the idea that someone with Strength of Stone could be affected by the Sleep opcode. You are still affected by the Gust of Wind (knocked down in place), just not moved by it. Strength of Stone is not a high-level spell after all. Something more powerful like Iron Body should protect against both, I think...

As far as implementation, why not break out the insect-dispelling bit into its own subspell? That would surely also have use elsewhere, might as well make it a portable effect...

**Comment by lambda-dom** [comment]
> I don't completely hate the idea that someone with Strength of Stone could be affected by the Sleep opcode. You are still affected by the Gust of Wind (knocked down in place), just not moved by it. Strength of Stone is not a high-level spell after all. Something more powerful like Iron Body should protect against both, I think...
> 
Arguably, unconsciouness is a side-effect of knocking; so no knocking, no unconsciousness. This probably has to be hashed out on a case-by-case basis as Bartimeus said.

> As far as implementation, why not break out the insect-dispelling bit into its own subspell? That would surely also have use elsewhere, might as well make it a portable effect...
Insect stuff cannot be handled by patching spells at the source as it is done further down the line in the code dealing with it (in lib/insects.tph and maybe elsewhere). Will get to it. Eventually.

**Comment by lambda-dom** [comment]
Will wait a couple more days, but with the sunscorch RFC is implemented, so if there are no objections merging this PR in a couple of days.

**Pull request merged**
