### PR TITLE
Arcane level 4 spell fixes

### PR DESCRIPTION
**Pull request by lambda-dom**
## Arcane Level 4 spell fixes.

1. Ice Sorm: fix duration of movement rate penalty 24 -> 7. See Kjeron's comments in the [SR fixes questions](https://www.gibberlings3.net/forums/topic/30963-sr-fixes-questions/) thread.
2. Minor Globe of Invulnerability: remove spurious double fireball protection. Change description to mention correct duration of 2 turns.
3. Contagion: Opcode's power 3 -> 4. Casting spell opcodes cast non-existent sppr311d -> dvpr311d, which is what cleric's version uses. resist_dispel 1 -> 0 on cast spell opcodes. Can target invisible for some unfathomable reason -> toggle the flag.
4. Break Enchantment: add remove charmed icon opcodes. Clarified description to mention it removes petrification.
5. Emotion, Despair: ac penalty opcode in first header has wrong duration.
6. Greater Malison: change description to mention correct duration of 2 turns.
7. Otiluke's Sphere: several problems. First, the same spwi413d.spl is cast (through an eff) on friends and enemies: clone spwi413d -> spwi413c and patch corresponding eff. Second, the friendly aux spell spwi413d resist_dispel -> 3 (one opcode has 1), while the hostile version spwi413c resist_dispel -> 1. COPY the aux spl in main_component.

note(s):
* fixing the spells at the source. If patching is done further down the line, then this fix should be removed, or at the very least revisited.

8. Spirit Armor: power of protection from spells 3 -> 4.
9. Fire Shield: protection against insect spells have incorrect durations.
10. Teleport Field: mention in description it bypasses mr.
11. Farsight: farsight opcode resist/dispel -> 2. Remove clairvoyance opcode as it serves no purpose (vanilla implementation does not use it).
12. Vitriolic Sphere: scroll has incorrect inventory and ability icons.

## B. TODO(s).

1. Greater Malison: the extra spell damage is implemented with luck -1 and then there is a thac0 +1 to counteract. But luck has more effects, should these be counteracted too? Following the IESDP, the obvious candidates are using 285, 286 to counteract weapon damage, skill opcodes and maybe 190?
2. Monster Summoning IV: effects "spidgisu" and "spidswsu" have incorrect power but these are vanilla, so can only be patched in-code. But power 8 on summoning eff's is harmless, so no urgency.

### CODE REVIEW

**Comment by subtledoctor** [comment]
Re: Greater Malison: first, I don't like the reference to "subtly control the flow of time" in the spell description - sounds like an Alteration spell, but this is in the Enchantment school. 

Second, adding bonuses to certain stats does not exactly offset Luck. Luck is weird. If anything, I would simply give a full and proper -1 Luck penalty to the spell. It wouldn't be unbalancing IMHO.

**Comment by BartyMae** [comment]
In regards to the Luck bonus, I would also say just mention it in the description. SRR's description of this spell:

"The spell allows the caster to adversely affect the saving throws of their enemies. The effect is applied to all hostile creatures within the area of effect. Those under the influence of this spell make all their saving throws at a penalty of -2, and suffer a -1 penalty to luck. Multiple castings of this spell are not cumulative."

**Comment by subtledoctor** [comment]
Yes, Demi intentionally toned down the spell from the vanilla -4 penalty. I think -2 to saves across the board plus a -1 luck penalty is balanced, since there is no way to block this spell.  Apart from MR, I guess. In fact as I think about it, I would probably set this to bypass MR. Maybe even reduce MR by 10% or so, which would be about the same magnitude as the luck and save penalties.

The main question about the luck penalty, which we discussed in a forum thread I think, is whether it steps on the toes of Waves of Fatigue. Personally, I don't think it does; why not combine the two spells, just as you can combine Malison and Doom for extra saving throw penalties?

**Comment by BartyMae** [comment]
I still have no idea what to do with Waves of Fatigue. I kind of hate that spell, especially because it replaces Chaos for both the player and especially the AI, who get hosed into using it when it was intended to be Chaos. Always been tempted to just restore Chaos over it in SRR, as lame as of a Greater Confusion it essentially is.

**Comment by subtledoctor** [comment]
Maybe put Waves of Fatigue (or something else entirely) at 4th level replacing Confusion, and put Confusion in place of Chaos at 5th level. That would slightly close the outrageous gap between wizards' Confusion and clerics' Confusion.

**Comment by BartyMae** [comment]
Hmm, that's actually a pretty good idea...maybe either make the duration of the spell 1 turn or perhaps give additional saving throw penalty scaling in exchange for going up a level (level 12 -3, level 15 -4?). Don't believe Clerics have Confusion in SR, though, so that is kind of besides the point (replaced with Sphere of Chaos AKA Chaos, IIRC). This change is more suited for either SRR or your own set of spell tweaks IMO, though.

**Comment by lambda-dom** [comment]
> Yes, Demi intentionally toned down the spell from the vanilla -4 penalty. I think -2 to saves across the board plus a -1 luck penalty is balanced, since there is no way to block this spell. Apart from MR, I guess. In fact as I think about it, I would probably set this to bypass MR. Maybe even reduce MR by 10% or so, which would be about the same magnitude as the luck and save penalties.
>

Whadda ya know, for some reason I thought it bypassed mr, but it does not. 

> The main question about the luck penalty, which we discussed in a forum thread I think, is whether it steps on the toes of Waves of Fatigue. Personally, I don't think it does; why not combine the two spells, just as you can combine Malison and Doom for extra saving throw penalties?

What do you mean by "why not combine the two spells, just as you can combine Malison and Doom for extra saving throw penalties?" Stack both for extra luck penalty?

**Comment by subtledoctor** [comment]
Yes, exactly that: allow Malison & Waves of Fatigue (plus Chant!) to stack for a greater combined luck penalty. I mean, they already do stack, so I’m not proposing anything; just arguing to not worry about how to ‘off-set’ the luck penalty in Malison.

**Comment by lambda-dom** [comment]
> Yes, exactly that: allow Malison & Waves of Fatigue (plus Chant!) to stack for a greater combined luck penalty. I mean, they already do stack, so I’m not proposing anything; just arguing to not worry about how to ‘off-set’ the luck penalty in Malison.

RFC time then. And put on it bypassing mr, which is an idea I like.
P.S.: just in case anyone is wondering, have not posted on the forums, because I am having trouble doing it. Argent77 mentioned somewhere a bug in Firefox, but I am on arch with latest Firefox so it *should* have been fixed.

**Comment by BartyMae** [comment]
> 
> 
> > Yes, exactly that: allow Malison & Waves of Fatigue (plus Chant!) to stack for a greater combined luck penalty. I mean, they already do stack, so I’m not proposing anything; just arguing to not worry about how to ‘off-set’ the luck penalty in Malison.
> 
> RFC time then. And put on it bypassing mr, which is an idea I like.
> P.S.: just in case anyone is wondering, have not posted on the forums, because I am having trouble doing it. Argent77 mentioned somewhere a bug in Firefox, but I am on arch with latest Firefox so it _should_ have been fixed.

I am a Firefox user on Windows and have not had any issues, but I am using the last version of Firefox (88.0.1) before their recent disaster of a UI update, might have something to do with it.

**Comment by subtledoctor** [comment]
I'm on Firefox on MacOS and the forums seem fine to me.  (But I have no idea how updated my Firefox is. I update when it suggests I do, but I don't pay attention to how often that is.)

**Pull request merged**
