### PR TITLE
Arcane level 6 spell fixes

### PR DESCRIPTION
**Pull request by lambda-dom**
## Arcane Level 6 spell fixes.

1. Invisible Stalker: summoning eff power -> 0.
2. Globe of Invulnerability: fix description that duration is 2 turns.
3. Tenser's Transformation: play visual effect resist/dispel 2 -> 3.
4. Flesh to Stone: In the aux spell all opcodes have instantaneous timing, but with a duration 12, which is harmless, but technically incorrect. Contrary to what is explicitly stated in the description, all opcodes have resist_dispel 1 -> 2.

note(s):
* see [Level 6 Spell Fixes](https://github.com/Gibberlings3/SpellRevisions/pull/34) for discussion.

5. Banishment: Fixed bam.
6. Protection from Magic Energy: contrary to what is stated, no creatures are immune to this spell -> fixed description.
7. Pierce Magic: incorrect duration of display portrait and play sound opcodes. Mind Blank is incorrectly listed as dispelled.
8. True Seeing: same fixes as in the cleric version. Specifically: immunity to blindness lacks the appropriate protection from icon and string opcodes. resist_dispel on the opcodes is also inconsistent: some are not dispellable, others like the delayed cast spell and aesthetic opcodes are, which makes no sense. Lacks protection from obscuring mist.
9. Protection from Magic Weapons: deleted first protection opcode against *magical* weapons of enchantment 0 and 0 duration.
10. Power Word Silence: changed display string "Silence" to "Silenced".
11. Improved Haste: repeated protection against slow removed and protection against non-existent spwi545 -> changed to spwm164.
12. Contingency: Last cast spell opcode removed.

note(s):
* See discussion below.

13. Monster Summoning VI: summoning eff power -> 0.
14. Conjure Fire Elemental: same problem as Conjure Lesser Fire Elemental: wrong probabilities in first visual opcode. Summoning eff power 6 -> 0.
15. Conjure Air Elemental: see Conjure Fire Elemental. Summoning eff power 6 -> 0.
16. Conjure Earth Elemental: see Conjure Fire Elemental. Summoning eff power 6 -> 0.
17. Animate Skeleton Warrior: Use Eff resist/dispel 3 -> 0. Summoning eff power 3 -> 0. Fixed bam.

### CODE REVIEW

**Comment by BartyMae** [comment]
Banishment: I'll re-post what I said last time: "Extra one is probably for no-limit summonables added by other mods [i.e. they have a different gender set in order to escape the normal limit]." It _likely_ should not be removed.

Protection from Magical Weapons: Certain spell "weapons" (e.g. Sol's Searing Orb) seemed to have been set to an enchantment level of higher than +5, presumably deliberately to pierce through Protection from Magical Weapons. By enabling the blanket magical weapon protection instead of sticking with the original +1-5 protections, such spell weapons will no longer pierce as seems to have been intended. However...this system is very IR-centric, because regular +6 items exist in vanilla (and presumably from other mod-added sources) but not appear whatsoever in IR (+5 is the max). I believe what I opted to do was instead set such spell weapons to +10 and extend Protection from Magical Weapons up to +9 instead. ...Turns out, I got half of that right - I did set such weapons to +10, but forgot to ever extend Protection from Magical Weapons up to 9 like I thought I did. Whoops.

Contingency: Assuming I'm understanding you correctly, I believe the delayed cast spell opcode is actually a weird and indirect way of playing a graphical effect after the contingency has been created (the white swirly cast graphic). Said effect does not come from SR, but is actually there in both the original Contingency and Chain Contingency in vanilla ToB games. However, the EE devs removed it. I don't feel too strongly either way, because it is such an oddball thing, but it is original spell behavior.

**Comment by lambda-dom** [comment]
Banishment: forgot that. Will revert.
PfMW: my bad, I misunderstood how the protection from weapons (120) opcode works. Deleting it instead of patching. Will leave the protection at max level 6.
Contingency: it casts spin905 which is a spell with no projectile or opcodes. Do subspells cast via 146 or 148 play their casting animations? That is the only option left for it to do anything.

**Comment by BartyMae** [comment]
If not set to instantly cast, then yes.

**Comment by subtledoctor** [comment]
Yes, the Contingency subspell is just to create the visual of the caster standing there waving their arms for a few seconds, even the the actual spell takes effect instantly. IIRC a savvy player can click the caster and just walk away in the middle of it. 

(Always struck me as dumb - why just give the spell a long casting time? But that’s neither here nor there.)

**Pull request merged**
