### PR TITLE
Level 6 spell fixes

### PR DESCRIPTION
**Pull request by lambda-dom**
- Tenser's Transformation: play visual effect resist/dispel 2 -> 3.
- Flesh to Stone: My first fix was not really a fix, and there were more problems than I initially caught. Main spell: the second remove spell type opcode for k1#haste has inconsistent resist_dispel, timing mode limited and a duration. But since it is added at install time, it cannot be solved by the simple patching means I am using. In the aux spell all opcodes have permanent timing, but with a duration 12, which is harmless, but confused the heck out of me for a moment so I ended up correcting it. Contrary to what is explicitly stated in the docs, all opcodes have resist_dispel 1, changed it to 2 so that they are not dispellable. The limited duration effects still have resist_dispel 1 => still dispellable and do not bypass mr. This includes the delayed cast opcode spell, which implies that the impending petrification can be prevented by a dispel. I assume this is what the developers intended, and also because of Barty_Mae's arguments, and leaving it alone.
- True Seeing (Wizard): like with the cleric version: blindness immunity and detect invisible are not dispellable but the delayed cast spell opcodes are so changed the resist_dispel -> 2. Finally, immunity to blindness lacks the appropriate protection from icon and string opcodes. Lacks protection from cleric's obscuring mist (assumes fixed resource name).
- Power Word Silence: changed display string "Silence" to "Silenced".
- Improved Haste: repeated protection against slow (removed) and protection against non-existent spwi545 -> changed to spwm164.
- Conjure Fire Elemental: same problem as Conjure Lesser Fire Elemental: wrong probabilities in first visual opcode -- see level 5 PR.
- Conjure Air Elemental: see Conjure Fire Elemental.
- Conjure Earth Elemental: see Conjure Fire Elemental.
- Animate Skeleton Warrior (Wizard): Use Eff resist/dispel 3 -> 2.
- Heal: add missing remove poisoned icon opcode.
- False Dawn: all but the first cast spell opcodes have magic resist 3. It makes no sense to me that these should be dispelled so changed resist -> 0 but if I am wrong, by all means undo the change.
- Dolorous Decay: play visual effect has a save penalty -5 -> 4. Damage amount of disease was 2 -> 1. Second display icons has timing mode 4 and duration 0. This smells like a mistake, and that it should be timing 0 with duration 60 -- changed.
- Physical Mirror: power of opcodes in aux spell sppr613d 1 -> 6.
- Regeneration (druid version): the description explicitly mentions the possibility of dispellability but opcodes have resist_dispel 0 -> 3. Contrary to other spells it is stackable with lower level regen spells, so added the right protections.
- Animate Skeleton Warrior (Cleric): Use Eff resist/dispel 3 -> 2, power 0 -> 6.

Description Fixe(s):
- Globe of Invulnerability: fix description that duration is 2 turns.
- Conjure Animals: description lacks mountain bear stats. Done nothing. Edit: if I am not mistaken, spell deprecated, so there is nothing to change.
- Dolorous Decay: mention it bypasses mr.
- Regeneration: description fix that duration is 3 turns.

Note(s):
- Banishment: second Use Eff against non-existent (unknown) in gender.ids. Done nothing.
- Protection from Magic Energy: contrary to what is stated in the docs, no creatures are immune to this spell; at least there are none of the usual Use Eff to set up immunities. Done nothing.
- Pierce Magic: aux spell display portrait icon and play sound have durations 72 -> 12. Unfortunately I have not caught any SR patching or copying, so it seems this is vanilla. I suggest then to move the fix to some component of SR.
- Contingency: three headers why? Last cast spell opcode for what? Although these all seem spurious, done nothing.
- Banishment (cleric): same problems as wizard's Banishment.

### CODE REVIEW

**Comment by BartyMae** [comment]
Flesh to Stone: By changing its dispel to 3, haven't you made it so that characters petrified can be cured by a simple dispel magic?
Banishment: Extra one is probably for no-limit summonables added b y other mods.

**Comment by lambda-dom** [comment]
> Flesh to Stone: By changing its dispel to 3, haven't you made it so that characters petrified can be cured by a simple dispel magic?

The change was 1 -> 3, which means it was already dispellable. But as you point out, and the docs explicitly mention: "A dispel magic spell cannot restore the victim's natural form, but some powerful spells, such as Stone to Flesh or Freedom, can." This means that I have to fix the aux spell as all well as the opcodes there have resist_dispel 1 -> 2. The question is if the limited duration effects should be dispellable: my answer is yes. The question of 1 vs. 3 was just because there is an inconsistency in the opcodes, but here the wrong reading was mine as resist_dispel 3 should only apply to the remove protection opcodes. And change the delayed cast spell opcode to 2.

Sigh.

**Comment by BartyMae** [comment]
So my feeling is, spwi604 should be 1: shouldn't bypass MR, but if you cast a Dispel Magic before SPWI604D is triggered, the petrification can be averted. SPWI604D, on the other hand, once the petrification has occurred, it should not be dispelable, which is a 2.

But you're not incorrect: the official version of SR has spwi604d set to 1, which means a simple Dispel Magic does indeed cure petrification (which I just tested and confirmed). I believe it should be set to 2 (which, as far as I know, is equivalent to 0, non-magical?) - it should not be dispelable after it has occurred, and the MR check is already done via the "cast spell" opcode in the base spwi604 spell, so it shouldn't have to pass MR again. I looked at basilisk attacks just to make sure this is true for more than spwi604 - the cast spell opcode they use there is also a 1, so again, the MR check is already baked in and doesn't need to be repeated for spwi604d.

**Comment by lambda-dom** [comment]
So I will keep resist_dispel 3 on the remove spell protection opcode (the spell is just mimicking slow and that is how it is done there), and do the other changes to the aux spell. As far as I know resist_dispel 0 and 2 are functionally equivalent; I use the first for item equipped opcodes and the second for spells, but that is just to keep things clear in my head.

So the only possible point of contention is whether the petrification can be averted by dispelling before the round is over. I will go with your opinion, and also because that is how things are set originally, so arguably that is what the authors intended.

**Comment by BartyMae** [comment]
"k1#haste opcode" This is just added because SPWI604 uses the slow opcode (40), which Spell Revisions uses to automatically dispel any non-improved Haste effects. Its dispel type and saving throw should automatically be cloned from whatever the slow effect itself is set to.

On a side-note, I forgot how overzealous the slow patching is - literally any spell or item effect that has opcode 40 (slow) will have its secondary type set to the slow, even if it's a minor part of the overall spell. So that's why I guess I always external slow effects to a secondary subspell.

**Pull request closed without merging**
