### PR TITLE
Arcane level 1 fixes

### PR DESCRIPTION
**Pull request by lambda-dom**
# Arcane Level 1 spell fixes.

1. Mage Armor: fix protection from spell opcode's target and power and add parameter1 = 74011 = "You cannot cast this spell until the current casting has run out." to it. Add protection against armor spells (Spirit Armor does it).
2. True Strike: target preset -> self.
3. Sleep: First header misses display portrait icon. First header display string "spell ineffective" resist_dispel -> 0. Headers other than first miss display string "spell ineffective" opcode.
4. Chill Touch: create item opcode amount 0 -> 1.
5. Charm Person: add Display String 1476 = Charmed.
6. Obscuring Mist: same fixes as Cleric version. See [Divine level 1 spell fixes](https://github.com/Gibberlings3/SpellRevisions/pull/46). Fixed bam with messed up transparency layer by using SRR bam.
7. Monster Summoning I: corrected power 6 -> 0 of summoning effect.
8. Expeditious Retreat: resist_dispel is all over the place. Standardized -> 3 since it targets party.
9. Shield: play sound resist_dispel 1 -> 3. Added protection against TRAP_MAGIC_MISSILE. Add parameter1 = 74011 = "You cannot cast this spell until the current casting has run out." to protection from spell for non-stacking.
10. Spook: display string opcode resist_dispel 0 -> 1.

### CODE REVIEW

**Comment by mike1072** [comment]
All of the files in the commit have a single quote at the end of their filenames, so this is being treated as introducing new files rather than changing the existing ones.

**Comment by lambda-dom** [comment]
Grrr, a dangling ' in the WeiDU code. Fixing asap.

**Comment by lambda-dom** [comment]
I will do a squash before committing to keep the git history clean.

**Comment by BartyMae** [comment]
Only tangentially related to your fixes, but I think SR should consider making it so that the Charm series of spells results in a non-hostile reaction once the charm effect has ended for BG1's sake: lots of Charm-specific dialogue in that game that you cannot realistically access when the spell irreversibly and unavoidably always causes hostility to the charmed NPC.

**Comment by lambda-dom** [comment]
I will keep that in mind.

**Comment by subtledoctor** [comment]
> SR should consider making it so that the Charm series of spells results in a non-hostile reaction once the charm effect has ended for BG1's sake: lots of Charm-specific dialogue in that game

I still think it's worth discussing whether/how to make Charm more like a localized Friends effect, than "Domination at 1st level." I know we never found a solution that Demi liked and/or that would play nice with SCS... but I hate this spell as it exists in this engine, and I still hope to find a valid modification of it. Maybe drastically reduce the duration. Heck, maybe it should just be replaced altogether. Give Friends the Charm effect to get that BG1 dialogue.

**Comment by lambda-dom** [comment]
> I still think it's worth discussing whether/how to make Charm more like a localized Friends effect, than "Domination at 1st level." I know we never found a solution that Demi liked and/or that would play nice with SCS... but I hate this spell as it exists in this engine, and I still hope to find a valid modification of it. Maybe drastically reduce the duration. Heck, maybe it should just be replaced altogether. Give Friends the Charm effect to get that BG1 dialogue.

Agreed. I would suggest changing the charm type of the spells Charm Person (wizard, level 1) and *maybe* Charm Person or Mammal (cleric, level 2). Since this is a tweak, I will open an RFC.

**Comment by lambda-dom** [comment]
Deferring the charm stuff to a new PR and merging this.

**Pull request merged**
