### PR TITLE
Divine level 2 fixes

### PR DESCRIPTION
**Pull request by lambda-dom**
## Divine Level 2 spells.

1. Charm Person or Animal: add Display String 1476 = Charmed.
2. Find Traps: subspell timing = instantaneous. Target preset -> self.
3. Flame Blade: create item opcode amount 0 -> 1.
4. Hold Person: play sound opcode has a save bonus of -1. Added display string 14102 = "Held" opcode.
5. Know Opponent: description fix: casting speed 1 round -> 2. Implementation of golem immunity as a spurious protection against Wizard version of the spell. Description fix: casting speed 1 round -> 2.
6. Slow Poison: add remove intoxicated icon opcode since the spell also cures intoxication. Add remove poisoned icon opcode for the same reason.
7. Spiritual Hammer: create item opcode amount 0 -> 1.
8. Draw upon Divine Might: remove cast spell dvwinded. Winded at the end of DuDM is undocumented, a relic of earlier SR versions.
9. Cure Moderate Wounds: add remove intoxicated icon opcode since the spell also cures intoxication.
10. Regenerate Moderate Wounds: power of opcodes 1 -> 2, resist_dispel 0 -> 3. Add Display String "Regenerating" for consistency with Regenerate Light Wounds.
11. Gust of Wind: sleep opcode resist_dispel 0 -> 1. Changed implementation to use a subspell as needed by Strength of Stone -- see the PR [Divine level 1 spell fixes](https://github.com/Gibberlings3/SpellRevisions/pull/46) for more details.

note(s):
* Gust of Wind: add to description that it dispels insect swarms. But this is done elsewhere, in the code dealing with the insect stuff, so leaving it for later -- note to future self.

12. Cause Moderate Wounds: power 0 -> 2.
13. Animal Summoning II: summoning eff power 8 -> 0.

### Long implementation note for Gust of Wind.

Moved the Wing Buffet (235) and Sleep (39) opcodes to a subspell. Started with Bartimeus version in SRR, named there as "dvgustwi" and here "dvknbck" (reason for renaming below), and then patched it.

My first criterion was, and since this subspell will likely be useful in other situations, to make a sort of reference implementation -- this is the reason for renaming "dvgustwi" to "dvknbck" (7 characters, leaves one character to name versions of the subspell). I want "a subspell implementing the knockback + unconsciousness effect" not a "subspell of Gust of Wind to be used in this particular situation". The first step was do some clean up on SRR version: the most important was to zero out the projectile as the parent projectile is already doing all the necessary filtering (and as a general thumbrule, subspells should not have projectiles, unless you really really need them).

note(s):
* I could be misinterpreting how the "away from source" parameter in Wing Buffet (235) works. I am assuming the source means the caster, as per the IESDP: "Applies the wing buffet effect centred on the casting creature(s)".

Per the IESDP, sectype and school were kept so that relevant immunities and interaction with certain opcodes works. Range (header field) was set to 1000, since range checks are otiose when casting through an opcode and for all I know may even be detrimental.

As far as the substance of the spell itself, I have reverted strength of Wing Buffet which is 15 instead of SRR's 10 (doing fixes only, not tweaks). Also keeping the "Wake on damage = yes" although I tend to view unconsciousness as separate from sleep precisely by this flag. More substantial I have added racial immunities to Dragons and Giants via the usual (that is, working in classical and EE versions) Use Eff -> protection from spell with timing duration. Immunity for dragons is most likely redundant, but redundancy in this specific case is harmless and even good as it communicates developer intent to the poor sod that picks up maintenance. If you judge any more should be added, shout.

Finally, there is always the vexing question of where to put certain things like power, saves, resist_dispel, etc., in the spell itself or in the casting opcode. I tend to favor the latter for the following reason: since I want a reference implementation, I want to patch this spell as little as possible when clone-ing it for other uses, and therefore it makes sense to move as much as possible to the casting opcode. This works well for saves and power, but not for resist_dispel, because in general, there are timed opcodes in the subspell that we want to be dispellable. In this particular case, since the knockback is caused by wind, a physical effect, I would have used resist_dispel = 0 that is, not dispellable and bypass mr, but since the original has resist_dispel = 1 using that in the spell itself and resist_dispel = 0 in the casting opcode. The casting opcode has parameter1 = 0 and parameter2 = 1, which means cast instantly at caster level = level 1 since subspell has only one level 1 header. This is the general case for subspells, they usually do not have any scaling and oinly one level 1 header.

### CODE REVIEW

**Comment by BartyMae** [comment]
>Finally, there is always the vexing question of where to put certain things like power, saves, resist_dispel, etc., in the spell itself or in the casting opcode.

It should basically always be the latter. Thus the saving throw/resistability/power level is always consistent with the casting spell/ability/attack, which is especially important if you want a generic resource like this to be potentially used by multiple sources. In particular cases where this is not true and you need e.g. the dispel status to be different from the casting spell, it necessitates a separate resource.

>Find Traps: auxiliary spell duration 20 -> 6 as the spell is delayed cast in intervals of 6. Target preset -> self.

I remember you noting this one a long time ago in your original PR, and I remember wondering if the duration has any effect on how long traps remain revealed to begin with, AND whether or not 20 is how long the normal Thief's Detect Traps reveals traps. If the duration actually does affect that and the latter is true, they should probably stay at 20. If the duration does not functionally change anything, perhaps it should just be set to permanent. I'll test it later today.

**Comment by BartyMae** [comment]
Well, I went and investigated Find Traps finally, and discovered that it seems like once a trap is discovered, it is discovered permanently. Leaving the area or reloading the game strikes the red highlight, but the trap remains discovered - you can still use your Thieving skill on a discovered trap even if it's no longer highlighted red. So I suppose the duration is completely pointless, since it's permanent regardless.

**Comment by lambda-dom** [comment]
> Well, I went and investigated Find Traps finally, and discovered that it seems like once a trap is discovered, it is discovered permanently. Leaving the area or reloading the game strikes the red highlight, but the trap remains discovered - you can still use your Thieving skill on a discovered trap even if it's no longer highlighted red. So I suppose the duration is completely pointless, since it's permanent regardless.

According to the IESDP "This effect is automatically successful, but can only find traps that are normally detectable by the Find Traps skill. ", so changing the timing of the opcode to instantaneous and cleaning out the duration.

**Comment by subtledoctor** [comment]
Probably neither here nor there: I have a "Cast at Point" version of Gust of Wind with the Sleep/Buffet effects in a subspell, and I *think* "away from source" knocks things away from the point you cast it at. (So you could theoretically knock things back toward you.)

Not really relevant here since Wind Gust is cast on self, but yes, this will knock everyone away from the caster, in all directions.

I don't know about making numbered versions of the subspell, but keeping it to 7 letters is a good idea (it's pretty much always a good idea with .SPL files, regardless of what they are or do). Moreover, it's probably worth adding that subspell to the NWN-style Deflection list (which only works for files with 7 or fewer letters).

**Pull request merged**
